apiVersion: v1
data:
  AMQ_CLUSTER_PASSWORD: d2MyVVFsS2M=
  AMQ_CLUSTER_USER: czZXZEZlNUQ=
  AMQ_PASSWORD: YWRtaW4xMjM=
  AMQ_USER: YWRtaW4=
kind: Secret
metadata:
  labels:
    ActiveMQArtemis: artemis
    application: artemis-app
  name: artemis-credentials-secret
type: Opaque