apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      ActiveMQArtemis: artemis
      application: artemis-app
    name: artemis-hdls-svc
  spec:
    clusterIP: None
    ports:
    - name: http-console-jolokia
      port: 8161
      protocol: TCP
      targetPort: 8161
    - name: tcp-acceptor
      port: 61616
      protocol: TCP
      targetPort: 61616
    selector:
      ActiveMQArtemis: artemis
      application: artemis-app
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      ActiveMQArtemis: artemis
      application: artemis-app
    name: artemis-ping-svc
  spec:
    clusterIP: None
    internalTrafficPolicy: Cluster
    ports:
    - name: tcp-ping
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      ActiveMQArtemis: artemis
      application: artemis-app
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      ActiveMQArtemis: artemis
      application: artemis-app
    name: artemis-tcp-acceptor-0-svc
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - name: tcp-acceptor-0
      port: 61616
      protocol: TCP
      targetPort: 61616
    publishNotReadyAddresses: true
    selector:
      ActiveMQArtemis: artemis
      application: artemis-app
      statefulset.kubernetes.io/pod-name: artemis-ss-0
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      ActiveMQArtemis: artemis
      application: artemis-app
    name: artemis-tcp-acceptor-1-svc
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - name: tcp-acceptor-1
      port: 61616
      protocol: TCP
      targetPort: 61616
    publishNotReadyAddresses: true
    selector:
      ActiveMQArtemis: artemis
      application: artemis-app
      statefulset.kubernetes.io/pod-name: artemis-ss-1
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      ActiveMQArtemis: artemis
      application: artemis-app
    name: artemis-wconsj-0-svc
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - name: http-console-jolokia
      port: 8161
      protocol: TCP
      targetPort: 8161
    publishNotReadyAddresses: true
    selector:
      ActiveMQArtemis: artemis
      application: artemis-app
      statefulset.kubernetes.io/pod-name: artemis-ss-0
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      ActiveMQArtemis: artemis
      application: artemis-app
    name: artemis-wconsj-1-svc
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - name: http-console-jolokia
      port: 8161
      protocol: TCP
      targetPort: 8161
    publishNotReadyAddresses: true
    selector:
      ActiveMQArtemis: artemis
      application: artemis-app
      statefulset.kubernetes.io/pod-name: artemis-ss-1
    sessionAffinity: None
    type: ClusterIP
kind: List
