apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      ActiveMQArtemis: artemis
      application: artemis-app
    name: artemis-artemis-ss-0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      ActiveMQArtemis: artemis
      application: artemis-app
    name: artemis-artemis-ss-1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
kind: List