kind: ActiveMQArtemis
apiVersion: broker.amq.io/v1beta1
metadata:
  name: artemis
spec:
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 2
    enableMetricsPlugin: true
    annotations:
      prometheus.io/path: /metrics/
      prometheus.io/port: '8162'
      prometheus.io/scheme: http
      prometheus.io/scrape: 'true'
      traffic.sidecar.istio.io/excludeInboundPorts: '7800'
  env:
  - name: JAVA_ARGS_APPEND
    value: >-
      -Dwebconfig.bindings.my-binding.uri=http://localhost:8162
      -Dwebconfig.bindings.my-binding.apps.my-app.url=metrics
      -Dwebconfig.bindings.my-binding.apps.my-app.war=metrics.war
      