apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: amq
spec:
  gateways:
  - mesh
  hosts:
  - artemis-hdls-svc
  tcp:
  - route:
    - destination:
        host: artemis-hdls-svc
        port:
          number: 61616
      weight: 100

